// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHEfhr9nZsQSxWA_c9hcgz8WQHVhqBYvI',
    appId: '1:300539705025:web:48d847ecc4084516a64640',
    messagingSenderId: '300539705025',
    projectId: 'sortit-c9771',
    authDomain: 'sortit-c9771.firebaseapp.com',
    storageBucket: 'sortit-c9771.firebasestorage.app',
    measurementId: 'G-QWBHJCLBV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuuo3iDqiap9v9M2FL1oVUrLAteEW0EM',
    appId: '1:300539705025:android:61cec5362ac4b637a64640',
    messagingSenderId: '300539705025',
    projectId: 'sortit-c9771',
    storageBucket: 'sortit-c9771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFC0ZlNhP8LYPzUvmFpfhKsuLXBb2j9a8',
    appId: '1:300539705025:ios:d6c91372139e1aa3a64640',
    messagingSenderId: '300539705025',
    projectId: 'sortit-c9771',
    storageBucket: 'sortit-c9771.firebasestorage.app',
    iosBundleId: 'com.example.sortit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFC0ZlNhP8LYPzUvmFpfhKsuLXBb2j9a8',
    appId: '1:300539705025:ios:d6c91372139e1aa3a64640',
    messagingSenderId: '300539705025',
    projectId: 'sortit-c9771',
    storageBucket: 'sortit-c9771.firebasestorage.app',
    iosBundleId: 'com.example.sortit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHEfhr9nZsQSxWA_c9hcgz8WQHVhqBYvI',
    appId: '1:300539705025:web:60c07eee680774a8a64640',
    messagingSenderId: '300539705025',
    projectId: 'sortit-c9771',
    authDomain: 'sortit-c9771.firebaseapp.com',
    storageBucket: 'sortit-c9771.firebasestorage.app',
    measurementId: 'G-6V4SJT05GW',
  );
}
